In [1]:
import glob
import pandas as pd

In [2]:
#This is the ridership data (smaller csv files)
bike_ridership_data = pd.concat([pd.read_csv(f) for f in glob.glob('data/bike_membership/*.csv')], ignore_index = True)

In [3]:
bike_ridership_data.count()

Date                                                  90
Trips over the past 24-hours (midnight to 11:59pm)    90
Miles traveled today (midnight to 11:59 pm)           90
Total Annual Members (All Time)                       90
24-Hour Passes Purchased (midnight to 11:59 pm)       90
3-Day Passes Purchased (midnight to 11:59 pm)         90
dtype: int64

In [4]:
bike_ridership_data.head(50)

,Date,Trips over the past 24-hours (midnight to 11:59pm),Miles traveled today (midnight to 11:59 pm),Total Annual Members (All Time),24-Hour Passes Purchased (midnight to 11:59 pm),3-Day Passes Purchased (midnight to 11:59 pm)
0,1/1/2018,5499,11483,253490,123,7
1,1/2/2018,18818,39352,253558,125,12
2,1/3/2018,24299,42853,253591,164,4
3,1/4/2018,1922,5328,253604,2,1
4,1/5/2018,4972,14303,253614,14,0
5,1/6/2018,4294,9479,253624,9,2
6,1/7/2018,5640,9387,253640,41,4
7,1/8/2018,15820,31294,253661,45,4
8,1/9/2018,25090,50981,253690,112,17
9,1/10/2018,28252,50218,253720,142,18
10,1/11/2018,33961,66584,253757,244,15
11,1/12/2018,22252,46403,253786,152,16
12,1/13/2018,17758,30418,253809,355,31
13,1/14/2018,12394,32949,253827,183,9
14,1/15/2018,17637,41770,253857,150,8
15,1/16/2018,30278,60053,253895,189,13
16,1/17/2018,19010,36319,253921,52,12
17,1/18/2018,27662,52573,253952,92,18
18,1/19/2018,30525,50322,253983,216,15
19,1/20/2018,28507,59336,254025,1044,41
20,1/21/2018,27908,61571,254092,1013,26
21,1/22/2018,36864,68638,254144,345,25
22,1/23/2018,28796,63693,254191,179,19
23,1/24/2018,36078,69596,254236,232,32
24,1/25/2018,31147,51927,254263,181,16
25,1/26/2018,33073,61857,254301,313,23
26,1/27/2018,34348,70146,254368,1415,41
27,1/28/2018,20100,38221,254415,334,22
28,1/29/2018,36799,68868,254466,274,33
29,1/30/2018,27996,59260,254492,114,15
30,1/31/2018,31276,54440,254539,141,19
31,2/1/2018,35561,66984,254590,212,27
32,2/2/2018,26313,50427,254620,129,18
33,2/3/2018,18385,40020,254640,263,23
34,2/4/2018,13959,35121,254670,224,7
35,2/5/2018,29068,56061,254725,193,21
36,2/6/2018,34102,68060,254760,160,18
37,2/7/2018,15289,31573,254781,30,4
38,2/8/2018,31563,60985,254806,168,20
39,2/9/2018,31567,57070,254833,223,25
40,2/10/2018,16323,37641,254857,343,26
41,2/11/2018,8809,21167,254877,85,2
42,2/12/2018,35138,68283,254922,339,40
43,2/13/2018,35189,69420,254968,252,31
44,2/14/2018,39591,80081,255002,408,39
45,2/15/2018,44193,88474,255044,501,28
46,2/16/2018,29191,57219,255088,316,37
47,2/17/2018,17921,38834,255118,537,51
48,2/18/2018,21537,50512,255151,938,40
49,2/19/2018,25677,62150,255217,553,50

In [5]:
bike_ridership_data.tail(50)

,Date,Trips over the past 24-hours (midnight to 11:59pm),Miles traveled today (midnight to 11:59 pm),Total Annual Members (All Time),24-Hour Passes Purchased (midnight to 11:59 pm),3-Day Passes Purchased (midnight to 11:59 pm)
40,2/10/2018,16323,37641,254857,343,26
41,2/11/2018,8809,21167,254877,85,2
42,2/12/2018,35138,68283,254922,339,40
43,2/13/2018,35189,69420,254968,252,31
44,2/14/2018,39591,80081,255002,408,39
45,2/15/2018,44193,88474,255044,501,28
46,2/16/2018,29191,57219,255088,316,37
47,2/17/2018,17921,38834,255118,537,51
48,2/18/2018,21537,50512,255151,938,40
49,2/19/2018,25677,62150,255217,553,50
50,2/20/2018,44478,98129,255306,906,85
51,2/21/2018,53110,118306,255430,1596,77
52,2/22/2018,27010,54857,255485,147,18
53,2/23/2018,25633,49639,255534,165,22
54,2/24/2018,25550,61251,255597,956,51
55,2/25/2018,16149,34052,255654,231,18
56,2/26/2018,42570,84614,255747,448,54
57,2/27/2018,48514,107682,255836,664,48
58,2/28/2018,50707,100855,255944,637,52
59,3/1/2018,45562,91489,256022,571,45
60,3/2/2018,6855,23277,256050,21,7
61,3/3/2018,28361,61107,256117,851,56
62,3/4/2018,25262,60490,256189,704,33
63,3/5/2018,36774,75190,256263,357,47
64,3/6/2018,42688,80995,256307,516,27
65,3/7/2018,8188,22312,256333,16,7
66,3/8/2018,28440,53403,256360,188,17
67,3/9/2018,34912,70068,256393,344,43
68,3/10/2018,25443,59343,256438,689,43
69,3/11/2018,27596,67622,256517,1173,46
70,3/12/2018,36339,76569,256578,351,39
71,3/13/2018,23137,46021,256623,133,14
72,3/14/2018,35377,62352,256673,269,39
73,3/15/2018,39572,72192,256724,462,66
74,3/16/2018,34921,62381,256763,383,55
75,3/17/2018,27671,62524,256823,1015,56
76,3/18/2018,25158,55182,256880,839,36
77,3/19/2018,39278,83086,256933,544,39
78,3/20/2018,35532,69573,256986,187,17
79,3/21/2018,3755,11799,257004,3,1
80,3/22/2018,27308,61715,257040,216,25
81,3/23/2018,38527,77668,257098,543,55
82,3/24/2018,34396,79562,257167,1755,88
83,3/25/2018,25562,62656,257226,710,24
84,3/26/2018,40295,88831,257315,718,87
85,3/27/2018,41354,88986,257378,524,63
86,3/28/2018,41880,80607,257447,586,64
87,3/29/2018,39288,84590,257501,544,65
88,3/30/2018,34784,78825,257584,1006,147
89,3/31/2018,41779,109399,257701,3856,151

In [6]:
#This is the trip data(bigger csv files)
bike_trip_data = pd.concat([pd.read_csv(f) for f in glob.glob('data/bike_trip/*.csv')], ignore_index = True)

In [7]:
bike_trip_data.count()

tripduration               2538780
starttime                  2538780
stoptime                   2538780
start station id           2538780
start station name         2538780
start station latitude     2538780
start station longitude    2538780
end station id             2538780
end station name           2538780
end station latitude       2538780
end station longitude      2538780
bikeid                     2538780
usertype                   2538780
birth year                 2538780
gender                     2538780
dtype: int64

In [8]:
bike_trip_data.head(50)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1
5,1602,2018-01-01 21:31:54.1920,2018-01-01 21:58:36.3530,72,W 52 St & 11 Ave,40.767272,-73.993929,482,W 15 St & 7 Ave,40.739355,-73.999318,30106,Subscriber,1968,1
6,722,2018-01-02 07:54:53.6460,2018-01-02 08:06:55.8720,72,W 52 St & 11 Ave,40.767272,-73.993929,228,E 48 St & 3 Ave,40.754601,-73.971879,32059,Subscriber,1978,1
7,434,2018-01-02 08:06:14.3310,2018-01-02 08:13:28.7670,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,30525,Subscriber,1983,1
8,366,2018-01-02 08:10:15.2550,2018-01-02 08:16:21.8960,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,27439,Subscriber,1974,1
9,324,2018-01-02 08:13:30.8960,2018-01-02 08:18:55.1200,72,W 52 St & 11 Ave,40.767272,-73.993929,450,W 49 St & 8 Ave,40.762272,-73.987882,30892,Subscriber,1947,1
10,1155,2018-01-02 09:15:29.9050,2018-01-02 09:34:45.0200,72,W 52 St & 11 Ave,40.767272,-73.993929,347,Greenwich St & W Houston St,40.728846,-74.008591,31591,Subscriber,1982,1
11,1200,2018-01-02 10:23:18.8800,2018-01-02 10:43:18.9110,72,W 52 St & 11 Ave,40.767272,-73.993929,127,Barrow St & Hudson St,40.731724,-74.006744,30257,Subscriber,1974,1
12,732,2018-01-02 11:52:37.5540,2018-01-02 12:04:49.8800,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32649,Subscriber,1969,1
13,600,2018-01-02 12:20:57.0070,2018-01-02 12:30:57.0180,72,W 52 St & 11 Ave,40.767272,-73.993929,457,Broadway & W 58 St,40.766953,-73.981693,26964,Subscriber,1991,1
14,1058,2018-01-02 13:28:46.1540,2018-01-02 13:46:24.3070,72,W 52 St & 11 Ave,40.767272,-73.993929,523,W 38 St & 8 Ave,40.754666,-73.991382,32617,Subscriber,1947,1
15,256,2018-01-02 13:54:11.6460,2018-01-02 13:58:28.1980,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,31095,Subscriber,1978,1
16,318,2018-01-02 13:55:11.9200,2018-01-02 14:00:29.9410,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,31182,Subscriber,1963,1
17,694,2018-01-02 14:27:49.6230,2018-01-02 14:39:24.1270,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,32375,Subscriber,1967,1
18,604,2018-01-02 15:04:41.3810,2018-01-02 15:14:45.7090,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32505,Subscriber,1964,1
19,724,2018-01-02 15:25:00.5410,2018-01-02 15:37:05.3230,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,19512,Subscriber,1965,1
20,395,2018-01-02 15:37:55.9310,2018-01-02 15:44:31.0550,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,17881,Subscriber,1956,1
21,520,2018-01-02 16:09:21.1800,2018-01-02 16:18:02.0510,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,31426,Customer,1969,0
22,430,2018-01-02 16:10:59.3790,2018-01-02 16:18:10.0110,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,32349,Customer,1969,0
23,842,2018-01-02 16:34:16.2920,2018-01-02 16:48:18.6180,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,31019,Subscriber,1978,1
24,243,2018-01-02 16:36:12.6120,2018-01-02 16:40:15.7660,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,29984,Subscriber,1973,1
25,705,2018-01-02 16:36:14.3160,2018-01-02 16:47:59.7340,72,W 52 St & 11 Ave,40.767272,-73.993929,477,W 41 St & 8 Ave,40.756405,-73.990026,20922,Subscriber,1992,1
26,1163,2018-01-02 16:43:09.9290,2018-01-02 17:02:33.2530,72,W 52 St & 11 Ave,40.767272,-73.993929,3466,W 45 St & 6 Ave (OLD),40.756687,-73.982577,33277,Subscriber,1974,1
27,680,2018-01-02 16:58:34.7080,2018-01-02 17:09:55.0030,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,16425,Subscriber,1964,1
28,634,2018-01-02 17:04:25.6190,2018-01-02 17:14:59.7750,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,28382,Subscriber,1977,1
29,782,2018-01-02 17:13:04.4750,2018-01-02 17:26:06.8250,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,30649,Subscriber,1982,1
30,638,2018-01-02 17:15:42.2560,2018-01-02 17:26:21.1640,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,19809,Subscriber,1973,1
31,447,2018-01-02 17:30:34.4740,2018-01-02 17:38:01.8490,72,W 52 St & 11 Ave,40.767272,-73.993929,529,W 42 St & 8 Ave,40.757570,-73.990985,25609,Subscriber,1996,1
32,1450,2018-01-02 17:39:43.6510,2018-01-02 18:03:54.3190,72,W 52 St & 11 Ave,40.767272,-73.993929,3459,E 53 St & 3 Ave,40.757632,-73.969306,19627,Subscriber,1985,1
33,322,2018-01-02 18:01:36.1170,2018-01-02 18:06:58.3390,72,W 52 St & 11 Ave,40.767272,-73.993929,3236,W 42 St & Dyer Ave,40.758985,-73.993800,25137,Subscriber,1960,1
34,458,2018-01-02 18:02:48.5040,2018-01-02 18:10:27.0200,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,33185,Subscriber,1962,1
35,603,2018-01-02 18:24:18.6830,2018-01-02 18:34:21.8650,72,W 52 St & 11 Ave,40.767272,-73.993929,3233,E 48 St & 5 Ave,40.757246,-73.978059,33185,Subscriber,1959,1
36,658,2018-01-02 18:25:35.9430,2018-01-02 18:36:34.0990,72,W 52 St & 11 Ave,40.767272,-73.993929,465,Broadway & W 41 St,40.755136,-73.986580,31095,Subscriber,1965,1
37,307,2018-01-02 18:40:32.1030,2018-01-02 18:45:39.8450,72,W 52 St & 11 Ave,40.767272,-73.993929,450,W 49 St & 8 Ave,40.762272,-73.987882,19363,Subscriber,1991,1
38,652,2018-01-02 18:45:52.5360,2018-01-02 18:56:44.7950,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,29990,Subscriber,1969,1
39,1325,2018-01-02 19:11:45.3440,2018-01-02 19:33:51.1940,72,W 52 St & 11 Ave,40.767272,-73.993929,487,E 20 St & FDR Drive,40.733143,-73.975739,26382,Subscriber,1966,1
40,359,2018-01-02 19:49:25.3460,2018-01-02 19:55:25.1230,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,30487,Subscriber,1974,1
41,668,2018-01-02 20:00:36.6980,2018-01-02 20:11:45.4090,72,W 52 St & 11 Ave,40.767272,-73.993929,3233,E 48 St & 5 Ave,40.757246,-73.978059,33437,Subscriber,1957,1
42,362,2018-01-02 20:14:17.5950,2018-01-02 20:20:20.4820,72,W 52 St & 11 Ave,40.767272,-73.993929,469,Broadway & W 53 St,40.763441,-73.982681,28965,Subscriber,1979,1
43,665,2018-01-02 20:15:24.1260,2018-01-02 20:26:29.7260,72,W 52 St & 11 Ave,40.767272,-73.993929,359,E 47 St & Park Ave,40.755103,-73.974987,30710,Subscriber,1989,1
44,469,2018-01-02 20:21:38.1120,2018-01-02 20:29:27.3080,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,31279,Subscriber,1992,1
45,383,2018-01-02 21:09:14.4670,2018-01-02 21:15:37.6880,72,W 52 St & 11 Ave,40.767272,-73.993929,450,W 49 St & 8 Ave,40.762272,-73.987882,31311,Subscriber,1983,1
46,332,2018-01-02 22:39:52.0290,2018-01-02 22:45:24.7570,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,29737,Subscriber,1974,1
47,1134,2018-01-02 22:59:07.0100,2018-01-02 23:18:01.0620,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,30672,Subscriber,1973,1
48,496,2018-01-03 00:45:24.3200,2018-01-03 00:53:40.5420,72,W 52 St & 11 Ave,40.767272,-73.993929,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,30606,Subscriber,1992,1
49,386,2018-01-03 07:16:49.1700,2018-01-03 07:23:15.6090,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,33356,Subscriber,1974,1

In [9]:
bike_trip_data.tail(50)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2538730,645,2018-03-31 14:32:11.0390,2018-03-31 14:42:56.6340,3674,Jay St & York St,40.701403,-73.986727,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,31324,Subscriber,1988,2
2538731,693,2018-03-31 14:32:18.3380,2018-03-31 14:43:51.9300,3674,Jay St & York St,40.701403,-73.986727,361,Allen St & Hester St,40.716059,-73.991908,31032,Subscriber,1986,1
2538732,179,2018-03-31 14:42:23.6050,2018-03-31 14:45:22.7180,3674,Jay St & York St,40.701403,-73.986727,414,Pearl St & Anchorage Pl,40.702819,-73.987658,31294,Customer,1965,1
2538733,155,2018-03-31 14:42:55.3050,2018-03-31 14:45:31.0140,3674,Jay St & York St,40.701403,-73.986727,414,Pearl St & Anchorage Pl,40.702819,-73.987658,16876,Customer,1965,1
2538734,151,2018-03-31 14:42:59.9070,2018-03-31 14:45:31.8960,3674,Jay St & York St,40.701403,-73.986727,414,Pearl St & Anchorage Pl,40.702819,-73.987658,18794,Customer,1998,1
2538735,1068,2018-03-31 14:45:46.4730,2018-03-31 15:03:34.9070,3674,Jay St & York St,40.701403,-73.986727,335,Washington Pl & Broadway,40.729039,-73.994046,18682,Subscriber,1976,1
2538736,546,2018-03-31 14:48:59.2530,2018-03-31 14:58:06.1580,3674,Jay St & York St,40.701403,-73.986727,313,Washington Ave & Park Ave,40.696102,-73.967510,32868,Subscriber,1978,1
2538737,1184,2018-03-31 14:56:53.2080,2018-03-31 15:16:37.3400,3674,Jay St & York St,40.701403,-73.986727,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,29848,Subscriber,1988,1
2538738,1133,2018-03-31 14:57:13.3800,2018-03-31 15:16:06.9750,3674,Jay St & York St,40.701403,-73.986727,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,31928,Subscriber,1988,2
2538739,1901,2018-03-31 15:16:11.8060,2018-03-31 15:47:52.9790,3674,Jay St & York St,40.701403,-73.986727,3659,W 17 St & 9 Ave,40.742949,-74.004137,30795,Subscriber,1981,1
2538740,385,2018-03-31 15:17:55.7530,2018-03-31 15:24:21.3080,3674,Jay St & York St,40.701403,-73.986727,391,Clark St & Henry St,40.697601,-73.993446,25535,Subscriber,1968,2
2538741,837,2018-03-31 15:26:51.7600,2018-03-31 15:40:49.0170,3674,Jay St & York St,40.701403,-73.986727,386,Centre St & Worth St,40.714948,-74.002345,33106,Subscriber,1996,1
2538742,763,2018-03-31 15:42:58.7770,2018-03-31 15:55:42.4010,3674,Jay St & York St,40.701403,-73.986727,243,Fulton St & Rockwell Pl,40.688226,-73.979382,16623,Subscriber,1988,1
2538743,771,2018-03-31 15:42:58.6080,2018-03-31 15:55:49.9520,3674,Jay St & York St,40.701403,-73.986727,243,Fulton St & Rockwell Pl,40.688226,-73.979382,20071,Subscriber,1990,2
2538744,243,2018-03-31 15:44:32.6980,2018-03-31 15:48:36.0060,3674,Jay St & York St,40.701403,-73.986727,2001,Sands St & Navy St,40.699773,-73.979927,31401,Subscriber,1983,1
2538745,223,2018-03-31 15:44:56.1120,2018-03-31 15:48:39.8080,3674,Jay St & York St,40.701403,-73.986727,2001,Sands St & Navy St,40.699773,-73.979927,33363,Subscriber,1983,2
2538746,596,2018-03-31 15:51:51.7960,2018-03-31 16:01:48.2870,3674,Jay St & York St,40.701403,-73.986727,3402,Court St & State St,40.690238,-73.992031,20138,Subscriber,1985,2
2538747,572,2018-03-31 15:52:15.2770,2018-03-31 16:01:48.0000,3674,Jay St & York St,40.701403,-73.986727,3402,Court St & State St,40.690238,-73.992031,26781,Subscriber,1982,1
2538748,984,2018-03-31 15:54:31.7480,2018-03-31 16:10:56.6250,3674,Jay St & York St,40.701403,-73.986727,531,Forsyth St & Broome St,40.718939,-73.992663,31967,Subscriber,1975,1
2538749,941,2018-03-31 15:56:34.1200,2018-03-31 16:12:15.2960,3674,Jay St & York St,40.701403,-73.986727,3412,Pacific St & Nevins St,40.685376,-73.983021,29563,Subscriber,1985,1
2538750,929,2018-03-31 15:56:59.0550,2018-03-31 16:12:28.1190,3674,Jay St & York St,40.701403,-73.986727,3412,Pacific St & Nevins St,40.685376,-73.983021,32132,Customer,1969,0
2538751,715,2018-03-31 15:57:48.3220,2018-03-31 16:09:43.9950,3674,Jay St & York St,40.701403,-73.986727,323,Lawrence St & Willoughby St,40.692362,-73.986317,15489,Subscriber,1962,1
2538752,1525,2018-03-31 16:44:03.5210,2018-03-31 17:09:29.3050,3674,Jay St & York St,40.701403,-73.986727,3016,Kent Ave & N 7 St,40.720368,-73.961651,20828,Customer,1969,0
2538753,432,2018-03-31 16:46:01.5670,2018-03-31 16:53:13.6400,3674,Jay St & York St,40.701403,-73.986727,3402,Court St & State St,40.690238,-73.992031,25671,Subscriber,1979,1
2538754,928,2018-03-31 16:48:06.7240,2018-03-31 17:03:35.4450,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,14927,Customer,1969,0
2538755,901,2018-03-31 16:48:30.2040,2018-03-31 17:03:32.0750,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,29811,Customer,1969,0
2538756,778,2018-03-31 16:50:51.6350,2018-03-31 17:03:50.2470,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,32618,Customer,1969,0
2538757,775,2018-03-31 16:50:52.1610,2018-03-31 17:03:47.6840,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,27954,Customer,1969,0
2538758,361,2018-03-31 16:53:01.6890,2018-03-31 16:59:02.9310,3674,Jay St & York St,40.701403,-73.986727,2001,Sands St & Navy St,40.699773,-73.979927,25751,Subscriber,1956,1
2538759,416,2018-03-31 17:00:55.6840,2018-03-31 17:07:51.7330,3674,Jay St & York St,40.701403,-73.986727,3648,Flushing Ave & Vanderbilt Ave,40.697950,-73.970776,16422,Subscriber,1968,1
2538760,867,2018-03-31 17:02:36.3990,2018-03-31 17:17:04.0000,3674,Jay St & York St,40.701403,-73.986727,2009,Catherine St & Monroe St,40.711174,-73.996826,30767,Subscriber,1988,1
2538761,1369,2018-03-31 17:03:30.8940,2018-03-31 17:26:19.9700,3674,Jay St & York St,40.701403,-73.986727,3180,Brooklyn Bridge Park - Pier 2,40.698780,-73.997120,19492,Customer,1969,0
2538762,1345,2018-03-31 17:03:46.3210,2018-03-31 17:26:11.8170,3674,Jay St & York St,40.701403,-73.986727,3180,Brooklyn Bridge Park - Pier 2,40.698780,-73.997120,17777,Customer,1969,0
2538763,1347,2018-03-31 17:03:46.1470,2018-03-31 17:26:13.2010,3674,Jay St & York St,40.701403,-73.986727,3180,Brooklyn Bridge Park - Pier 2,40.698780,-73.997120,27741,Customer,1969,0
2538764,959,2018-03-31 17:04:10.1460,2018-03-31 17:20:09.2940,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,19405,Customer,1991,2
2538765,918,2018-03-31 17:04:49.8180,2018-03-31 17:20:08.6680,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,18386,Customer,1991,1
2538766,1562,2018-03-31 17:08:45.9960,2018-03-31 17:34:48.1130,3674,Jay St & York St,40.701403,-73.986727,307,Canal St & Rutgers St,40.714275,-73.989900,20120,Subscriber,1989,1
2538767,88,2018-03-31 17:10:52.2640,2018-03-31 17:12:20.6540,3674,Jay St & York St,40.701403,-73.986727,2000,Front St & Washington St,40.702551,-73.989402,30206,Subscriber,1979,1
2538768,1611,2018-03-31 17:35:27.1870,2018-03-31 18:02:18.9410,3674,Jay St & York St,40.701403,-73.986727,3092,Berry St & N 8 St,40.719009,-73.958525,29885,Customer,1969,0
2538769,1753,2018-03-31 17:37:10.0700,2018-03-31 18:06:23.7960,3674,Jay St & York St,40.701403,-73.986727,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,32378,Customer,1969,0
2538770,1707,2018-03-31 17:37:50.3980,2018-03-31 18:06:18.3000,3674,Jay St & York St,40.701403,-73.986727,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,26138,Customer,1969,0
2538771,2222,2018-03-31 17:39:39.4950,2018-03-31 18:16:41.5360,3674,Jay St & York St,40.701403,-73.986727,387,Centre St & Chambers St,40.712733,-74.004607,32314,Customer,1969,0
2538772,2183,2018-03-31 17:39:51.9280,2018-03-31 18:16:15.4170,3674,Jay St & York St,40.701403,-73.986727,387,Centre St & Chambers St,40.712733,-74.004607,31279,Customer,1969,0
2538773,530,2018-03-31 18:24:00.5260,2018-03-31 18:32:50.8310,3674,Jay St & York St,40.701403,-73.986727,412,Forsyth St & Canal St,40.715816,-73.994224,26355,Subscriber,1989,1
2538774,1211,2018-03-31 18:34:25.2900,2018-03-31 18:54:37.0620,3674,Jay St & York St,40.701403,-73.986727,3115,India St & Manhattan Ave,40.732322,-73.955086,27608,Subscriber,1992,1
2538775,515,2018-03-31 19:47:26.4920,2018-03-31 19:56:01.9420,3674,Jay St & York St,40.701403,-73.986727,313,Washington Ave & Park Ave,40.696102,-73.967510,31195,Subscriber,1963,1
2538776,446,2018-03-31 22:43:44.6140,2018-03-31 22:51:10.6930,3674,Jay St & York St,40.701403,-73.986727,313,Washington Ave & Park Ave,40.696102,-73.967510,15618,Subscriber,1983,1
2538777,277,2018-03-31 23:12:21.1530,2018-03-31 23:16:58.8590,3674,Jay St & York St,40.701403,-73.986727,391,Clark St & Henry St,40.697601,-73.993446,15660,Subscriber,1983,1
2538778,517,2018-03-31 23:26:29.5770,2018-03-31 23:35:07.2460,3674,Jay St & York St,40.701403,-73.986727,321,Cadman Plaza E & Red Cross Pl,40.699918,-73.989718,25195,Subscriber,1986,1
2538779,2219,2018-03-31 23:56:42.5160,2018-04-01 00:33:41.7410,3674,Jay St & York St,40.701403,-73.986727,317,E 6 St & Avenue B,40.724537,-73.981854,17883,Subscriber,1980,2

In [10]:
#Ridership dataframe to csv file
bike_ridership_data.to_csv("data/final/bike_membership_data_Q1_2018.csv")

In [11]:
#trip dataframe to csv file
bike_trip_data.to_csv("data/final/bike_trip_data_Q1_2018.csv")